name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker HUB
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-service-a
        uses: docker/metadata-action@v3
        with:
          images: cciobanu98/poc-service-a

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: src/PoC.ServiceA/Dockerfile
          context: src
          push: true
          tags: ${{ steps.meta-service-a.outputs.tags }}
          labels: ${{ steps.meta-service-a.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-service-b
        uses: docker/metadata-action@v3
        with:
          images: cciobanu98/poc-service-b

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: src/PoC.ServiceB/Dockerfile
          context: src
          push: true
          tags: ${{ steps.meta-service-b.outputs.tags }}
          labels: ${{ steps.meta-service-b.outputs.labels }}
          no-cache: true

      - name: Publish helm menu chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: deployment
          linting: off
