name: Release

on:
  push:
    branches:
      - main

jobs:
  operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker HUB
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-operator
        uses: docker/metadata-action@v3
        with:
          images: cciobanu98/poc-operator

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: src/PoC.Operator/Dockerfile
          context: src
          push: true
          tags: ${{ steps.meta-operator.outputs.tags }}
          labels: ${{ steps.meta-operator.outputs.labels }}

  tenant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker HUB
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-tenant
        uses: docker/metadata-action@v3
        with:
          images: cciobanu98/poc-tenant

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: src/PoC.Tenant/Dockerfile
          context: src
          push: true
          tags: ${{ steps.meta-tenant.outputs.tags }}
          labels: ${{ steps.meta-tenant.outputs.labels }}

  release:
    needs: [operator, tenant]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: deployment
          linting: off
